import 'dart:io';
import 'dart:typed_data';
import 'package:flutter/material.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:path_provider/path_provider.dart';
import 'package:permission_handler/permission_handler.dart';
import 'package:open_file/open_file.dart';
import 'package:intl/intl.dart';
import '../models/tenant.dart';
import '../models/room.dart';

class ReceiptService {
  static const String _receiptTemplate = '''
RECEIPT
TENANT VISION APP
Property Management System

Date: {date}
Receipt No: {receiptNumber}

Tenant Information:
Name: {tenantName}
Property: {propertyName}
Room: Room {roomNumber}
Phone: {phone}
Email: {email}

Payment Details:
Amount: TZS {amount}
Payment Date: {paymentDate}
Payment Method: Cash
Notes: {notes}

Thank you for your payment!

Generated by Tenant Vision App
''';

  /// Generates a PDF receipt for a payment
  static Future<String?> generateReceipt({
    required Payment payment,
    required Tenant tenant,
    required Room room,
    required String propertyName,
  }) async {
    try {
      debugPrint('Starting receipt generation for payment: ${payment.id}');
      
      // Always request storage permission for Android
      if (Platform.isAndroid) {
        final permission = await Permission.storage.request();
        debugPrint('Storage permission status: ${permission.toString()}');
        if (!permission.isGranted) {
          debugPrint('Storage permission denied: ${permission.toString()}');
          // Don't throw error immediately, try app-specific directory first
        }
      }

      // Create PDF document
      final pdf = pw.Document();
      
      // Add receipt content
      pdf.addPage(
        pw.Page(
          pageFormat: PdfPageFormat.a4,
          build: (pw.Context context) {
            return pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                // Header
                pw.Container(
                  width: double.infinity,
                  padding: const pw.EdgeInsets.all(20),
                  decoration: pw.BoxDecoration(
                    color: PdfColors.blue50,
                    border: pw.Border.all(color: PdfColors.blue200),
                  ),
                  child: pw.Column(
                    children: [
                      pw.Text(
                        'RECEIPT',
                        style: pw.TextStyle(
                          fontSize: 24,
                          fontWeight: pw.FontWeight.bold,
                          color: PdfColors.blue800,
                        ),
                      ),
                      pw.SizedBox(height: 8),
                      pw.Text(
                        'TENANT VISION APP',
                        style: pw.TextStyle(
                          fontSize: 16,
                          fontWeight: pw.FontWeight.bold,
                          color: PdfColors.blue700,
                        ),
                      ),
                      pw.Text(
                        'Property Management System',
                        style: pw.TextStyle(
                          fontSize: 12,
                          color: PdfColors.blue600,
                        ),
                      ),
                    ],
                  ),
                ),
                
                pw.SizedBox(height: 20),
                
                // Receipt details
                pw.Container(
                  padding: const pw.EdgeInsets.all(20),
                  child: pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.start,
                    children: [
                      // Receipt number and date
                      pw.Row(
                        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                        children: [
                          pw.Text(
                            'Receipt No: ${payment.id}',
                            style: pw.TextStyle(fontSize: 12, fontWeight: pw.FontWeight.bold),
                          ),
                          pw.Text(
                            'Date: ${DateFormat('MMM dd, yyyy').format(DateTime.now())}',
                            style: pw.TextStyle(fontSize: 12),
                          ),
                        ],
                      ),
                      
                      pw.SizedBox(height: 20),
                      
                      // Tenant information
                      pw.Text(
                        'Tenant Information:',
                        style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold),
                      ),
                      pw.SizedBox(height: 8),
                      pw.Text('Name: ${tenant.fullName}'),
                      pw.Text('Property: $propertyName'),
                      pw.Text('Room: Room ${room.roomNumber}'),
                      if (tenant.phone != null) pw.Text('Phone: ${tenant.phone}'),
                      if (tenant.email != null) pw.Text('Email: ${tenant.email}'),
                      
                      pw.SizedBox(height: 20),
                      
                      // Payment details
                      pw.Text(
                        'Payment Details:',
                        style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold),
                      ),
                      pw.SizedBox(height: 8),
                      pw.Text('Amount: TZS ${NumberFormat('#,##0').format(payment.amount)}'),
                      pw.Text('Payment Date: ${DateFormat('MMM dd, yyyy').format(payment.date)}'),
                      pw.Text('Payment Method: Cash'),
                      if (payment.notes != null && payment.notes!.isNotEmpty)
                        pw.Text('Notes: ${payment.notes}'),
                      
                      pw.SizedBox(height: 30),
                      
                      // Footer
                      pw.Center(
                        child: pw.Column(
                          children: [
                            pw.Text(
                              'Thank you for your payment!',
                              style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold),
                            ),
                            pw.SizedBox(height: 10),
                            pw.Text(
                              'Generated by Tenant Vision App',
                              style: pw.TextStyle(fontSize: 10, color: PdfColors.grey600),
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
              ],
            );
          },
        ),
      );

      // Try multiple directory options in order of preference
      Directory? directory;
      String? errorMessage;
      
      // First try: Downloads directory (if permission granted)
      try {
        final downloadsDir = await getDownloadsDirectory();
        if (downloadsDir != null) {
          final testFile = File('${downloadsDir.path}/test_write.txt');
          await testFile.writeAsString('test');
          await testFile.delete();
          directory = downloadsDir;
          debugPrint('Using downloads directory: ${directory.path}');
        }
      } catch (e) {
        debugPrint('Downloads directory not accessible: $e');
        errorMessage = e.toString();
      }
      
      // Second try: App documents directory (always accessible)
      if (directory == null) {
        try {
          directory = await getApplicationDocumentsDirectory();
          debugPrint('Using app documents directory: ${directory.path}');
        } catch (e) {
          debugPrint('App documents directory not accessible: $e');
          throw Exception('Cannot access any directory for saving files: $errorMessage');
        }
      }

      // Ensure directory exists
      if (!await directory.exists()) {
        await directory.create(recursive: true);
      }

      // Generate filename
      final fileName = 'receipt_${payment.id}_${DateFormat('yyyyMMdd_HHmmss').format(DateTime.now())}.pdf';
      final file = File('${directory.path}/$fileName');

      // Save PDF
      final pdfBytes = await pdf.save();
      await file.writeAsBytes(pdfBytes);
      
      debugPrint('Receipt saved successfully to: ${file.path}');
      return file.path;
    } catch (e) {
      debugPrint('Error generating receipt: $e');
      return null;
    }
  }

  /// Downloads and opens a receipt
  static Future<bool> downloadReceipt({
    required Payment payment,
    required Tenant tenant,
    required Room room,
    required String propertyName,
  }) async {
    try {
      debugPrint('Starting receipt download for payment: ${payment.id}');
      
      // First try to generate PDF receipt
      String? filePath = await generateReceipt(
        payment: payment,
        tenant: tenant,
        room: room,
        propertyName: propertyName,
      );

      // If PDF generation fails, try text receipt as fallback
      if (filePath == null) {
        debugPrint('PDF generation failed, trying text receipt fallback');
        filePath = await saveTextReceipt(
          payment: payment,
          tenant: tenant,
          room: room,
          propertyName: propertyName,
        );
      }

      if (filePath != null) {
        debugPrint('File generated successfully: $filePath');
        
        // Open the file
        final result = await OpenFile.open(filePath);
        debugPrint('Open file result: ${result.type} - ${result.message}');
        
        if (result.type == ResultType.done) {
          debugPrint('File opened successfully');
          return true;
        } else {
          debugPrint('Failed to open file: ${result.message}');
          // Try to copy to a more accessible location
          return await _copyToAccessibleLocation(filePath);
        }
      }
      
      debugPrint('No file path generated, download failed');
      return false;
    } catch (e) {
      debugPrint('Error downloading receipt: $e');
      return false;
    }
  }

  /// Helper method to copy file to a more accessible location
  static Future<bool> _copyToAccessibleLocation(String filePath) async {
    try {
      debugPrint('Attempting to copy file to accessible location: $filePath');
      
      final sourceFile = File(filePath);
      if (!await sourceFile.exists()) {
        debugPrint('Source file does not exist: $filePath');
        return false;
      }

      // Try to copy to external storage downloads folder
      final downloadsDir = await getDownloadsDirectory();
      if (downloadsDir != null) {
        final fileName = filePath.split('/').last;
        final destFile = File('${downloadsDir.path}/$fileName');
        
        debugPrint('Copying to: ${destFile.path}');
        await sourceFile.copy(destFile.path);
        
        // Try to open the copied file
        final result = await OpenFile.open(destFile.path);
        debugPrint('Open copied file result: ${result.type} - ${result.message}');
        return result.type == ResultType.done;
      }
      
      debugPrint('Downloads directory not available for copying');
      return false;
    } catch (e) {
      debugPrint('Error copying file to accessible location: $e');
      return false;
    }
  }

  /// Generates a simple text receipt (fallback if PDF fails)
  static String generateTextReceipt({
    required Payment payment,
    required Tenant tenant,
    required Room room,
    required String propertyName,
  }) {
    return '''
RECEIPT
TENANT VISION APP
Property Management System

Date: ${DateFormat('MMM dd, yyyy').format(DateTime.now())}
Receipt No: ${payment.id}

Tenant Information:
Name: ${tenant.fullName}
Property: $propertyName
Room: Room ${room.roomNumber}
${tenant.phone != null ? 'Phone: ${tenant.phone}' : ''}
${tenant.email != null ? 'Email: ${tenant.email}' : ''}

Payment Details:
Amount: TZS ${NumberFormat('#,##0').format(payment.amount)}
Payment Date: ${DateFormat('MMM dd, yyyy').format(payment.date)}
Payment Method: Cash
${payment.notes != null && payment.notes!.isNotEmpty ? 'Notes: ${payment.notes}' : ''}

Thank you for your payment!

Generated by Tenant Vision App
''';
  }

  /// Saves a text receipt to downloads folder
  static Future<String?> saveTextReceipt({
    required Payment payment,
    required Tenant tenant,
    required Room room,
    required String propertyName,
  }) async {
    try {
      debugPrint('Starting text receipt generation for payment: ${payment.id}');
      
      // Try multiple directory options in order of preference
      Directory? directory;
      String? errorMessage;
      
      // First try: Downloads directory (if permission granted)
      try {
        final downloadsDir = await getDownloadsDirectory();
        if (downloadsDir != null) {
          final testFile = File('${downloadsDir.path}/test_write.txt');
          await testFile.writeAsString('test');
          await testFile.delete();
          directory = downloadsDir;
          debugPrint('Using downloads directory for text: ${directory.path}');
        }
      } catch (e) {
        debugPrint('Downloads directory not accessible for text: $e');
        errorMessage = e.toString();
      }
      
      // Second try: App documents directory (always accessible)
      if (directory == null) {
        try {
          directory = await getApplicationDocumentsDirectory();
          debugPrint('Using app documents directory for text: ${directory.path}');
        } catch (e) {
          debugPrint('App documents directory not accessible for text: $e');
          throw Exception('Cannot access any directory for saving text files: $errorMessage');
        }
      }

      // Ensure directory exists
      if (!await directory.exists()) {
        await directory.create(recursive: true);
      }

      final fileName = 'receipt_${payment.id}_${DateFormat('yyyyMMdd_HHmmss').format(DateTime.now())}.txt';
      final file = File('${directory.path}/$fileName');

      final receiptText = generateTextReceipt(
        payment: payment,
        tenant: tenant,
        room: room,
        propertyName: propertyName,
      );

      await file.writeAsString(receiptText);
      debugPrint('Text receipt saved successfully to: ${file.path}');
      return file.path;
    } catch (e) {
      debugPrint('Error saving text receipt: $e');
      return null;
    }
  }

  // === Tenant Info PDF ===
  static Future<String?> generateTenantInfoPdf({
    required Tenant tenant,
    required Room room,
    required String propertyName,
    String? propertyAddress,
  }) async {
    try {
      if (Platform.isAndroid) {
        await Permission.storage.request();
      }

      final pdf = pw.Document();
      final currency = NumberFormat('#,##0');
      final dateFmt = DateFormat('MMM dd, yyyy');
      final balance = tenant.balance;

      pdf.addPage(
        pw.MultiPage(
          pageFormat: PdfPageFormat.a4,
          build: (context) => [
            pw.Header(
              level: 0,
              child: pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.start,
                    children: [
                      pw.Text('Tenant Information', style: pw.TextStyle(fontSize: 22, fontWeight: pw.FontWeight.bold)),
                      pw.SizedBox(height: 4),
                      pw.Text('Generated by Tenant Vision App'),
                    ],
                  ),
                  pw.Text(dateFmt.format(DateTime.now())),
                ],
              ),
            ),
            pw.Container(
              padding: const pw.EdgeInsets.all(8),
              decoration: pw.BoxDecoration(
                border: pw.Border.all(color: PdfColors.grey300),
                borderRadius: pw.BorderRadius.circular(6),
              ),
              child: pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  pw.Text('Property Details', style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold)),
                  pw.SizedBox(height: 6),
                  pw.Text('Name: $propertyName'),
                  if (propertyAddress != null) pw.Text('Address: $propertyAddress'),
                  pw.Text('Room: ${room.roomNumber}'),
                ],
              ),
            ),
            pw.SizedBox(height: 12),
            pw.Container(
              padding: const pw.EdgeInsets.all(8),
              decoration: pw.BoxDecoration(
                border: pw.Border.all(color: PdfColors.grey300),
                borderRadius: pw.BorderRadius.circular(6),
              ),
              child: pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  pw.Text('Tenant Details', style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold)),
                  pw.SizedBox(height: 6),
                  pw.Text('Name: ${tenant.fullName}'),
                  if (tenant.phone != null && tenant.phone!.isNotEmpty) pw.Text('Phone: ${tenant.phone}'),
                  if (tenant.email != null && tenant.email!.isNotEmpty) pw.Text('Email: ${tenant.email}'),
                  if (tenant.jobTitle != null && tenant.jobTitle!.isNotEmpty) pw.Text('Job: ${tenant.jobTitle}'),
                  pw.Text('Monthly Rent: TZS ${currency.format(tenant.monthlyRent)}'),
                  pw.Text('Start Date: ${dateFmt.format(tenant.startDate)}'),
                  pw.Text('Next Due Date: ${dateFmt.format(tenant.nextDueDate)}'),
                ],
              ),
            ),
            pw.SizedBox(height: 12),
            pw.Container(
              padding: const pw.EdgeInsets.all(8),
              decoration: pw.BoxDecoration(
                color: balance > 0 ? PdfColors.red50 : PdfColors.green50,
                border: pw.Border.all(color: balance > 0 ? PdfColors.red200 : PdfColors.green200),
                borderRadius: pw.BorderRadius.circular(6),
              ),
              child: pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  pw.Text('Summary', style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold)),
                  pw.Text(balance > 0
                      ? 'Outstanding Balance: TZS ${currency.format(balance)}'
                      : 'No outstanding balance'),
                ],
              ),
            ),
            pw.SizedBox(height: 12),
            pw.Text('Payment History', style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold)),
            pw.SizedBox(height: 6),
            if (tenant.payments.isEmpty)
              pw.Text('No payments recorded yet')
            else
              pw.Table.fromTextArray(
                headers: ['Date', 'Amount (TZS)', 'Notes'],
                data: tenant.payments.map((p) => [
                  dateFmt.format(p.date),
                  currency.format(p.amount),
                  p.notes ?? '-',
                ]).toList(),
                headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold),
                headerDecoration: const pw.BoxDecoration(color: PdfColors.grey200),
                cellAlignment: pw.Alignment.centerLeft,
                cellStyle: const pw.TextStyle(fontSize: 10),
                columnWidths: {
                  0: const pw.FlexColumnWidth(2),
                  1: const pw.FlexColumnWidth(2),
                  2: const pw.FlexColumnWidth(4),
                },
              ),
          ],
        ),
      );

      Directory? directory;
      try {
        final downloadsDir = await getDownloadsDirectory();
        if (downloadsDir != null) {
          directory = downloadsDir;
        }
      } catch (_) {}
      directory ??= await getApplicationDocumentsDirectory();

      if (!await directory.exists()) {
        await directory.create(recursive: true);
      }

      final fileName = 'tenant_info_${tenant.id}_${DateFormat('yyyyMMdd_HHmmss').format(DateTime.now())}.pdf';
      final file = File('${directory.path}/$fileName');
      await file.writeAsBytes(await pdf.save());
      return file.path;
    } catch (e) {
      debugPrint('Error generating tenant info PDF: $e');
      return null;
    }
  }

  static Future<bool> downloadTenantInfo({
    required Tenant tenant,
    required Room room,
    required String propertyName,
    String? propertyAddress,
  }) async {
    try {
      final path = await generateTenantInfoPdf(
        tenant: tenant,
        room: room,
        propertyName: propertyName,
        propertyAddress: propertyAddress,
      );
      if (path == null) return false;
      final result = await OpenFile.open(path);
      return result.type == ResultType.done;
    } catch (e) {
      debugPrint('Error downloading tenant info PDF: $e');
      return false;
    }
  }
}
}